edition: 1.0.0          #  命令行YAML规范版本，遵循语义化版本（Semantic Versioning）规范
name: sae-go-image       #  项目名称
access: "{{ access }}"  #  秘钥别名

services:
  function-test: #  服务名称
    component: sae@dev  # 组件名称
    props: #  组件的属性值
      region: "{{ region }}"
      application:
        name: "{{ appName }}"
        code:
          image: registry.cn-hangzhou.aliyuncs.com/namespace4sae/go-demo:v1
        port: 8080
